* README 简体中文
** 多语言与文本编码
目前仅README、CONTRIBUTING和HACKING提供且优先提供简体中文版。

其余文本文件除非特别声明，从文件名到内部仅会出现ASCII字符，所有文本文件按UTF-8编码，换行是Unix格式的LF。

** Q&As
*** tkt-ce是什么意思？
tkt是TanKetTou的简称，ce指社区版。

tankettou脱胎自tankette，读法参考日语并用长音收尾，指的是小型坦克或轻型装甲车，大小类似家用轿车。

项目名不承认除“タンケットー”、“tkt”、“tankettou”外任何指代，不接受任何向其他语言的翻译、音译、联想。

没有正式注册此名称为游戏名/商标名或利用此仓库为任何个人正式申请著作权的计划，但若届时发现恶意占据“タンケットー”、“tkt”、“tankettou”为游戏名或利用本仓库代码申请软著的行为将以此git仓库及附带的提交记录为证据提供。
*** tkt不是坦克堂的中文缩写吗？
并非。

实际上，虽然tkt在汉语拼音中的确和“坦克堂”的首字母雷同，且后者刚好是本项目建立起因（原qq欢乐坦克，后4399坦克堂停服），但这一点纯属巧合。同时，截至此项目仓库建立及撰写此说明，“タンケットー”、“tkt”、“tankettou”并不是任何注册商标、游戏名、保留名，所以本项目并不会因除“タンケットー”、“tkt”、“tankettou”外在任何文化任何语言下和已有注册标签含义上“撞脸”而更换称谓，任何相关的私下要求或水军刷屏将第一时间披露并永久保存在本仓库的SHAMEWALL文本文件中。

原本打算叫“坦克荣耀”或者“第坦人格”之类的，出于版权考量弃用，故目前选择用日文风格念英文单词tankette作为名称。

本项目与六次方公司等原4399坦克堂相关团体无任何关联，代码无原代码参考且全部自由开源，素材全部从0开始重新制作（素材默认由相应作者专有并授权给本仓库（包括为参与开发提交拉取请求而进行的fork仓库，不包括私人仓库、hard fork、换皮迭代等）作默认游戏素材使用，除非作者用附带其gpg签名（或作者在其它平台明确表示认可的其它身份验证方式）的文件明确许可外，禁止以任何理由用于其它用途（如训练模型、印制周边、模型输入、转载等）。

本项目虽然名称杂糅了日文和英文，且参与者目前全部为简中用户，但是与任何政府组织、民间组织均无关联，原则上不带政治色彩，但不保证游戏内容（如背景故事、场景样式）在部分解读下保持政治正确，不保证工作时安全，不保证合乎道德。

至于内容是否合适，将由真实玩家和开发者自愿参与集体表决，表决结果合适而第三方不可抗力判定不合适时所有参与表决的成员共同承担后果。
*** README、CONTRIBUTING和HACKING是什么？
这三个文本文件分别包含项目简介、贡献（参与开发）的规则和 如何 *HACK* 本项目。

项目简介你正在看，贡献规则主要说明一些规范，包括代码格式、素材格式等，HACKING简单说就是讲如何换皮、修改增删游戏内容之类的。
*** 那GitHub Wiki页需要看吗？
仔细看README、CONTRIBUTING、HACKING和可能的MANUAL（使用说明）的话就完全不用看那个。

使用GH wiki写部分指南只是为了阅读方便，毕竟很多时候不能对着电脑翻文本文件，在线用GitHub的wiki功能看会简单点，虽然内容没那么全。
*** 为什么要开这个项目？
目前开源社区没有易于使用的moba实现（可以查到个别但无一例外都是配合卖课的，连怎么用都只字未提，说白了作者就没打算让别人用），刚好借4399坦克堂倒闭契机开这个项目。

成，坦克堂玩家的童年回来了，自由软件社区多了一个moba实现，大家都收益。甚至通过换皮能做到类似ygopro和MDpro对战的情况，所有moba玩家都能拿不同皮肤在不同场景下玩。

不成，也不损失什么，更何况平面moba实现主要是需要总的投入精力过多，并没有技术上的硬性门槛，难听点说就是堆时间总能实现。
*** 单机没事，但如果数年后做了联机对战，如何防作弊？
本项目不考虑防作弊问题，信任客户端的计算结果，服务器（若有的话）仅用于沟通各客户端、断线重连、同步时间、管理AI行为等常见功能，联机公平性靠自觉。

防作弊最麻烦的地方在于常见的战争迷雾功能或局限视野怎么防客户端通过打补丁之类的办法关掉，由于本项目完全开放，只能想办法保证大家用的客户端完全一致且未被篡改，而这是不可能的，因为无论怎么做机器都在终端用户完全掌控下。

如确有需要将由志愿者在专门的fork（如“竞技版”）实现，客户端只负责绘制场景、处理用户输入和沟通服务端，完全不参与本地动画效果以外的任何计算，所有核心部分由中央服务器完成。这样玩家只要信任一台机器。

当然，这个中央服务器将需要高计算性能和好的网络状况，一般是局域网联机。
