* README 简体中文
** 多语言与文本编码
目前仅README、CONTRIBUTING和HACKING提供且优先提供简体中文版。

其余文本文件除非特别声明，从文件名到内部仅会出现ASCII字符，所有文本文件按UTF-8编码，换行是Unix格式的LF。

** Q&As
*** tkt-ce是什么意思？
tkt是TanKetTou的简称，ce指社区版。

tankettou脱胎自tankette，读法参考日语并用长音收尾，指的是小型坦克或轻型装甲车，大小类似家用轿车。

项目名不承认除“タンケットー”、“tkt”、“tankettou”外任何指代，不接受任何向其他语言的翻译、音译、联想。

没有正式注册此名称为游戏名/商标名或利用此仓库为任何个人正式申请著作权的计划，但若届时发现恶意占据“タンケットー”、“tkt”、“tankettou”为游戏名或利用本仓库代码申请软著的行为将以此git仓库及附带的提交记录为证据提供。

请注意，虽然tkt在汉语拼音是“坦克堂”的首字母，且后者刚好是本项目建立起因（原qq欢乐坦克，后4399坦克堂停服），但这一点纯属巧合。原本打算叫“坦克荣耀”或者“第坦人格”之类的，出于版权考量弃用，故目前选择用日文风格念英文单词tankette作为名称。

本项目与六次方公司等原4399坦克堂相关团体无任何关联，代码无原代码参考且全部自由开源，素材按玩家印象重新制作（素材可能禁止随意使用，但将提供方便的换皮指南作为补偿）。
*** README、CONTRIBUTING和HACKING是什么？
这三个文本文件分别包含项目简介、贡献（参与开发）的规则和 如何 *HACK* 本项目。
项目简介你正在看，贡献规则主要说明一些规范，包括代码格式、素材格式等，HACKING简单说就是讲如何换皮、修改增删游戏内容之类的。
*** 那GitHub Wiki页需要看吗？
仔细看README、CONTRIBUTING、HACKING和可能的MANUAL（使用说明）的话就完全不用看那个。

使用GH wiki写部分指南只是为了阅读方便，毕竟很多时候不能对着电脑翻文本文件，在线用GitHub的wiki功能看会简单点，虽然内容没那么全。
*** 为什么要开这个项目？
目前开源社区没有易于使用的moba实现（可以查到个别但无一例外都是配合卖课的，连怎么用都只字未提，说白了作者就没打算让别人用），刚好借4399坦克堂倒闭契机开这个项目。

成，坦克堂玩家的童年回来了，自由软件社区多了一个moba实现，大家都收益。甚至通过换皮能做到类似ygopro和MDpro对战的情况，所有moba玩家都能拿不同皮肤在不同场景下玩。

不成，也不损失什么，更何况平面moba实现主要是需要总的投入精力过多，并没有技术上的硬性门槛，难听点说就是堆时间总能实现。
